name: Post Check

on:
  push:
    branches:
      - mainnet
      - testnet
      - "feature/*"
      - "features/*"
      - "feat/*"
      - "feats/*"
  pull_request:
    branches:
      - mainnet
      - testnet
      - "feature/*"
      - "features/*"
      - "feat/*"
      - "feats/*"
      - "release/*"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest

    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Update package with soldeer
        run: forge soldeer update

      - name: Recursively update dependencies
        run: |
          chmod +x ./update-deps.sh
          ./update-deps.sh
        id: update-deps

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run PostCheck CI
        run: |
          export INFURA_API_KEY=${{env.INFURA_API_KEY}} && ./run.sh PostCheckCI -f ronin-mainnet -vvvv
        id: postcheck
